export CONTRIBDIR=contrib-2.1.0
export LWIPDIR=lwip/src
export TESTFLAGS="-DESP_LWIP=1 -DESP_DNS=0 -DESP_LWIP_IGMP_TIMERS_ONDEMAND=0 -DESP_LWIP_MLD6_TIMERS_ONDEMAND=0 -DLWIP_AUTOIP_MAX_CONFLICTS=10 -DLWIP_AUTOIP_RATE_LIMIT_INTERVAL=10 -DESP_LWIP_ARP=0"
export TEST_FILE="sockets/tcp_client"
